### ISSUE TITLE
(Windows) Extension blocks file picker from opening if clipboard contains a file

### ISSUE THREAD

**Issue by ahajishafieha** [daijro/Clipboard2File-Chrome#3]
OS: Windows 10
Browser: Edge 114.0.1823.43 & Chrome 114.0.5735.110

When the clipboard contains a file, the extension blocks the file picker dialog from opening when you click "browse" on a file input button.

To reproduce: 
1. Install the extension and companion software
2. Go to file explorer and choose any file (exe, pdf, zip, jpg, png, etc.), right click on it and press copy.
3. Open [testcase](https://jsfiddle.net/mox9ckua/)
4. Click the Choose File button.
5. Nothing happens.

Expected Results:
- If the clipboard contains a non-image file (exe, pdf, zip, etc.): Open the file picker dialog box directly
- If the clipboard contains an image file (jpg, png, webp, etc.): Show the extension's image upload dialog

Workaround:
Empty or change the clipboard contents to contain plain text or an image data

**Comment by daijro** [comment]
Fixed in the latest release 👍
